### ISSUE TITLE
Bump SDK Version

### ISSUE THREAD

**Issue by Globallager** [AztecProtocol/aztec-frontend-boilerplate#6]

**Comment by Globallager** [comment]
Stuck with `Cannot find module: '@aztec/sdk'. Make sure this package is installed.`.

**Comment by critesjosh** [comment]
looks like the location of barretenberg.wasm and web_worker.js changed again. i just installed 2.1.49 and the locations are ./node_modules/@aztec/barretenberg/dest/wasm/barretenberg.wasm ./node_modules/@aztec/barretenberg/dest/wasm/web_worker.js

**Comment by critesjosh** [comment]
i got a working version with SDK version 2.1.50 here https://github.com/critesjosh/cra5-aztec-boilerplate

**Comment by Globallager** [comment]
Was CRA5 the magic ingredient? Or was .50 simply fixed?

**Comment by critesjosh** [comment]
It was a combo of cra5, react app rewired and the config-overrides folder
in the project root.
